name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  workflow_dispatch:

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/ts-ci.yaml@98c2f685fa19abbbc43735b1108bfd53d30e65e0 # v1
    with:
      working-directory: "."
