name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: cplieger/ci/.github/workflows/release.yaml@2eaa3359c4d601496b2168cf4f8a474cd5a1c74b # v1
    secrets: inherit
