#!/usr/bin/env python3
"""Fail when source carries more than 0.55 comment lines per code line."""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import subprocess
import sys
import tokenize
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

COMMENT_CEILING = 0.5
MARGIN = 1.1
LIMIT = COMMENT_CEILING * MARGIN

EXCLUDED_REPOSITORIES = {
    'cplieger/.kiro',
    'cplieger/homelab',
    'cplieger/.github',
    'cplieger/ci',
}
SOURCE_SUFFIXES = {
    '.go',
    '.py',
    '.sh',
    '.bash',
    '.ts',
    '.tsx',
    '.mts',
    '.cts',
    '.js',
    '.jsx',
    '.mjs',
    '.cjs',
}
BLOCK_COMMENT_SUFFIXES = {'.go', '.ts', '.tsx', '.mts', '.cts', '.js', '.jsx', '.mjs', '.cjs'}
TEST_SEGMENTS = {
    'test',
    'tests',
    'testdata',
    'testsupport',
    'test-helpers',
    '__test-helpers__',
    '__snapshots__',
    'e2e',
    'authtest',
    'certtest',
    'testcerts',
    'plextest',
    'esctest',
}
JS_TEST_NAME = re.compile(r'\.(?:test|spec)\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$', re.IGNORECASE)
DOC_SEGMENTS = {'doc', 'docs', 'example', 'examples', 'sample', 'samples', 'demo', 'demos'}
GENERATED_SEGMENTS = {
    'vendor',
    'node_modules',
    'dist',
    'build',
    'generated',
    'gen',
    'third_party',
    '__pycache__',
}
GENERATED_NAME = re.compile(
    r'[._-](?:gen|generated)\.(?:go|py|sh|bash|ts|tsx|mts|cts|js|jsx|mjs|cjs)$',
    re.IGNORECASE,
)
GENERATED_HEADER = re.compile(
    r'(?:@generated\b|code[- ]generated\b|auto[- ]generated\b|autogenerated\b)',
    re.IGNORECASE,
)
DO_NOT_EDIT = re.compile(r'\bdo not edit\b', re.IGNORECASE)
EXAMPLE_NAME = re.compile(r'\.(?:example|sample)\.', re.IGNORECASE)
# Destinations sync.yaml copies verbatim from cplieger/ci. A consumer does not
# author these and must not edit its copy, so measuring them charges every
# adopting repo for prose written here — where this gate does not even run
# (cplieger/ci is in EXCLUDED_REPOSITORIES). Keyed on the consumer-side path
# because that is the tree being audited; keep in step with the sync map in
# scripts/classify-repos.py. eslint.config.base.mjs needs no entry: it is
# already caught by config_or_example.
SYNCED_PATHS = {
    'tests/image-smoke.sh',
    'tests/shell/lib.sh',
    'tests/shell/harness_test.sh',
    'scripts/repin-sha.sh',
}
HEREDOC_RE = re.compile(
    r"""(?<!<)<<-?\s*(?:
        \\(?P<escaped>[A-Za-z_][A-Za-z0-9_]*)
        |'(?P<single>[^']+)'
        |"(?P<double>[^"]+)"
        |(?P<plain>[A-Za-z_][A-Za-z0-9_]*)
    )""",
    re.VERBOSE,
)


@dataclass(frozen=True)
class FileCount:
    path: str
    comments: int
    code: int


@dataclass(frozen=True)
class Audit:
    files: tuple[FileCount, ...]
    excluded: Counter[str]

    @property
    def comments(self) -> int:
        return sum(item.comments for item in self.files)

    @property
    def code(self) -> int:
        return sum(item.code for item in self.files)

    @property
    def ratio(self) -> float:
        if self.code:
            return self.comments / self.code
        return float('inf') if self.comments else 0.0


def repository_name(root: Path) -> str:
    configured = os.environ.get('GITHUB_REPOSITORY', '').strip()
    if configured:
        return configured
    result = subprocess.run(
        ['git', 'remote', 'get-url', 'origin'],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode == 0:
        match = re.search(r'github\.com(?::|/)([^/]+/[^/]+?)(?:\.git)?$', result.stdout.strip())
        if match:
            return match.group(1)
    return ''


def visible_files(root: Path) -> list[Path]:
    result = subprocess.run(
        ['git', 'ls-files', '--cached', '--others', '--exclude-standard', '-z'],
        cwd=root,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.decode(errors='replace').strip() or 'git ls-files failed')
    return [
        root / item.decode(errors='surrogateescape') for item in result.stdout.split(b'\0') if item
    ]


def source_kind(path: Path) -> str | None:
    if path.name == 'Dockerfile' or path.name.startswith('Dockerfile.'):
        return 'hash'
    suffix = path.suffix.lower()
    if suffix not in SOURCE_SUFFIXES:
        return None
    if suffix in {'.py', '.sh', '.bash'}:
        return 'hash'
    return 'slash'


def test_source(path: Path) -> bool:
    parts = {part.lower() for part in path.parts[:-1]}
    name = path.name.lower()
    suffix = path.suffix.lower()
    if parts & TEST_SEGMENTS or name.endswith('_test.go') or JS_TEST_NAME.search(name):
        return True
    if suffix == '.py' and (name.startswith('test_') or name.endswith('_test.py')):
        return True
    if suffix in {'.sh', '.bash'}:
        stem = path.stem.lower()
        return stem.startswith(('test-', 'test_')) or stem.endswith(('-test', '_test', '.test'))
    return False


def config_or_example(path: Path) -> bool:
    name = path.name.lower()
    if EXAMPLE_NAME.search(name):
        return True
    if name.startswith('eslint.config.'):
        return True
    return bool(re.search(r'\.config\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$', name))


def exclusion(path: Path, text: str) -> str | None:
    parts = {part.lower() for part in path.parts[:-1]}
    if parts & GENERATED_SEGMENTS or GENERATED_NAME.search(path.name):
        return 'generated/vendor'
    header = '\n'.join(text.splitlines()[:10])
    if GENERATED_HEADER.search(header) and DO_NOT_EDIT.search(header):
        return 'generated/vendor'
    # Before the test_source early-return: three of the four synced paths live
    # under tests/, which that branch admits.
    if path.as_posix() in SYNCED_PATHS:
        return 'synced from cplieger/ci'
    if test_source(path):
        return None
    if parts & DOC_SEGMENTS:
        return 'docs/example'
    if config_or_example(path):
        return 'config/example'
    return None


def unescaped_count(text: str, token: str) -> int:
    count = 0
    for match in re.finditer(re.escape(token), text):
        backslashes = 0
        index = match.start() - 1
        while index >= 0 and text[index] == '\\':
            backslashes += 1
            index -= 1
        if backslashes % 2 == 0:
            count += 1
    return count


def heredoc_delimiters(text: str) -> list[str]:
    delimiters = []
    quote = ''
    index = 0
    while index < len(text):
        char = text[index]
        if quote:
            if char == '\\':
                index += 2
                continue
            if char == quote:
                quote = ''
            index += 1
            continue
        if char in '\'"':
            quote = char
            index += 1
            continue
        if char == '\\':
            index += 2
            continue
        if char == '#' and (index == 0 or text[index - 1].isspace()):
            break
        if text.startswith('<<', index):
            match = HEREDOC_RE.match(text, index)
            if match:
                delimiters.append(next(value for value in match.groupdict().values() if value))
                index = match.end()
                continue
        index += 1
    return delimiters


def unquoted_backtick_count(text: str) -> int:
    count = 0
    quote = ''
    index = 0
    while index < len(text):
        char = text[index]
        if quote:
            if char == '\\':
                index += 2
                continue
            if char == quote:
                quote = ''
            index += 1
            continue
        if text.startswith('//', index):
            break
        if text.startswith('/*', index):
            closing = text.find('*/', index + 2)
            if closing < 0:
                break
            index = closing + 2
            continue
        if char in '\'"':
            quote = char
        elif char == '`':
            count += 1
        elif char == '\\':
            index += 1
        index += 1
    return count


def scan_python(path: Path, text: str) -> FileCount:
    comments: set[int] = set()
    code: set[int] = set()
    lines = text.splitlines()
    ignored = {
        tokenize.ENCODING,
        tokenize.NL,
        tokenize.NEWLINE,
        tokenize.INDENT,
        tokenize.DEDENT,
        tokenize.ENDMARKER,
    }
    try:
        tokens = tokenize.generate_tokens(io.StringIO(text).readline)
        for token in tokens:
            if token.type == tokenize.COMMENT:
                comments.add(token.start[0])
                continue
            if token.type in ignored:
                continue
            for line in range(token.start[0], token.end[0] + 1):
                if 0 < line <= len(lines) and lines[line - 1].strip():
                    code.add(line)
    except (IndentationError, SyntaxError, tokenize.TokenError) as exc:
        raise RuntimeError(f'cannot tokenize {path}: {exc}') from exc
    if lines and lines[0].startswith('#!'):
        code.add(1)
        comments.discard(1)
    for line in (1, 2):
        if line <= len(lines) and re.search(r'coding[:=]\s*[-\w.]+', lines[line - 1]):
            code.add(line)
            comments.discard(line)
    return FileCount(str(path), len(comments - code), len(code))


def scan(path: Path, text: str, kind: str) -> FileCount:
    comments = 0
    code = 0
    in_block = False
    multiline_quote = ''
    heredocs: list[str] = []
    suffix = path.suffix.lower()
    if suffix == '.py':
        return scan_python(path, text)
    block_comments = suffix in BLOCK_COMMENT_SUFFIXES
    shell_like = kind == 'hash' and suffix != '.py'
    for index, raw in enumerate(text.splitlines()):
        stripped = raw.strip()
        if heredocs:
            if stripped:
                code += 1
            if raw.lstrip('\t').strip() == heredocs[0]:
                heredocs.pop(0)
            continue
        if multiline_quote:
            if stripped:
                code += 1
            if unescaped_count(raw, multiline_quote) % 2:
                multiline_quote = ''
            continue
        if not stripped:
            continue
        if in_block:
            comments += 1
            closing = stripped.find('*/')
            if closing >= 0:
                in_block = False
                if stripped[closing + 2 :].strip():
                    code += 1
            continue
        if index == 0 and stripped.startswith('#!'):
            code += 1
            continue
        if kind == 'hash':
            if stripped.startswith(('# syntax=', '# escape=')):
                code += 1
            elif stripped.startswith('#'):
                comments += 1
                continue
            else:
                code += 1
            if shell_like:
                heredocs.extend(heredoc_delimiters(raw))
            continue
        if stripped.startswith('//'):
            comments += 1
            continue
        if block_comments and stripped.startswith('/*'):
            comments += 1
            closing = stripped.find('*/', 2)
            if closing >= 0:
                if stripped[closing + 2 :].strip():
                    code += 1
            else:
                in_block = True
            continue
        code += 1
        if unquoted_backtick_count(raw) % 2:
            multiline_quote = '`'
    return FileCount(str(path), comments, code)


def audit(root: Path) -> Audit:
    files: list[FileCount] = []
    excluded: Counter[str] = Counter()
    for path in visible_files(root):
        kind = source_kind(path)
        if kind is None:
            continue
        relative = path.relative_to(root)
        if path.is_symlink():
            excluded['symlink'] += 1
            continue
        if not path.exists():
            excluded['deleted'] += 1
            continue
        try:
            text = path.read_text(encoding='utf-8', errors='replace')
        except OSError as exc:
            raise RuntimeError(f'cannot read {relative}: {exc}') from exc
        reason = exclusion(relative, text)
        if reason:
            excluded[reason] += 1
            continue
        files.append(scan(relative, text, kind))
    return Audit(tuple(files), excluded)


def emit(result: Audit, github: bool) -> int:
    ratio = result.ratio
    summary = (
        f'{result.comments} comment lines / {result.code} code lines = {ratio:.3f}:1; '
        f'limit {LIMIT:.2f}:1 across {len(result.files)} source files'
    )
    excluded = ', '.join(f'{name}={count}' for name, count in sorted(result.excluded.items()))
    if excluded:
        print(f'Excluded files: {excluded}')
    if not result.files or result.code == 0:
        message = 'no executable code lines found; add the repository to the non-app denylist if intentional'
        print(f'Comment ratio: FAIL — {message}')
        if github:
            print(f'::error title=Comment ratio::{message}')
        return 1
    if ratio <= LIMIT:
        print(f'Comment ratio: PASS — {summary}')
        if github:
            print(f'::notice title=Comment ratio::{summary}')
        return 0
    message = f'Comment ratio: FAIL — {summary}'
    print(message)
    print('Largest comment contributors:')
    for item in sorted(result.files, key=lambda value: value.comments, reverse=True)[:10]:
        if item.comments:
            file_ratio = item.comments / item.code if item.code else float('inf')
            display_path = json.dumps(item.path, ensure_ascii=True)
            print(
                f'  {display_path}: {item.comments} comments / {item.code} code = '
                f'{file_ratio:.2f}:1'
            )
    if github:
        print(f'::error title=Excessive comments::{summary}')
    return 1


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('path', nargs='?', default='.')
    parser.add_argument('--github', action='store_true')
    args = parser.parse_args(argv)
    root = Path(args.path).resolve()
    repository = repository_name(root)
    if repository in EXCLUDED_REPOSITORIES:
        message = f'{repository} is excluded because it is not an app repository'
        print(f'Comment ratio: SKIP — {message}')
        if args.github:
            print(f'::notice title=Comment ratio::{message}')
        return 0
    try:
        result = audit(root)
    except RuntimeError as exc:
        print(f'comment audit: {exc}', file=sys.stderr)
        return 2
    return emit(result, args.github)


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
