#!/usr/bin/env python3
"""Auto-discover and profile all cplieger repos, emitting .github/sync.yml.

Python port of the retired classify-repos.sh, preserving its discovery
filters, classification logic, cliff-tier selection, repo ordering, and YAML
output byte-for-byte. The manifest goes to STDOUT (sync.yaml redirects it to
.github/sync.yml — a gitignored runtime artifact, never committed); per-repo
diagnostics go to stderr.

Note: per-type ci.yaml templates (ci-go, ci-shell, ci-ts-lib) were retired in
favor of a single unified ci.yml that targets the central detect-and-dispatch
ci.yaml workflow in cplieger/ci. ALL releaseable repos receive the same
ci.yaml; the central workflow auto-detects surfaces (go.mod / jsr.json /
Dockerfile / nested web frontend) and runs the right jobs in parallel. No
more bespoke per-repo ci.yaml.

Auth: every GitHub read goes through the ambient `gh` CLI credentials
(GH_TOKEN / SYNC_PAT in CI); no token handling here.

Failure model: the initial `gh repo list` aborts the run on error or timeout
(exit code propagated; 124 on timeout, like GNU timeout), and it aborts on
hitting the --limit ceiling. Per-repo TREE reads degrade to a safe fallback —
an unreadable repo classifies as lang=none and drops out of every group
(mirrors the bash). The TAGS read is the exception and aborts on failure:
misreading it does not degrade, it picks the WRONG cliff tier and the sync
auto-merges the wrong cliff.toml (a hardening over the fail-open bash).

Run:
  scripts/classify-repos.py > .github/sync.yml
"""

import json
import subprocess
import sys

OWNER = 'cplieger'
TIMEOUT = 10  # seconds per API call

CI_FILES = """\
    files:
      - .editorconfig
      - .gitattributes
      - LICENSE
      - source: .github/workflow-templates/ci.yml
        dest: .github/workflows/ci.yaml
      - source: .github/workflow-templates/codeql.yml
        dest: .github/workflows/codeql.yml
      - source: .github/workflow-templates/security.yml
        dest: .github/workflows/security.yml
      - source: .github/workflow-templates/scorecard.yml
        dest: .github/workflows/scorecard.yml
      - source: configs/renovate.json
        dest: renovate.json"""

GOLANGCI_FILES = """\
    files:
      - .golangci.yaml
      - source: configs/gremlins.yaml
        dest: .gremlins.yaml"""

COVERAGE_FILES = """\
    files:
      - source: .github/workflow-templates/coverage.yml
        dest: .github/workflows/coverage.yml"""

SMOKE_FILES = """\
    files:
      - source: configs/image-smoke.sh
        dest: tests/image-smoke.sh"""

PYTHON_FILES = """\
    files:
      - .editorconfig
      - .gitattributes
      - source: configs/ruff.toml
        dest: ruff.toml"""

TS_CONFIG_FILES = """\
    files:
      - source: configs/eslint.config.base.mjs
        dest: eslint.config.base.mjs
      - source: configs/prettier.json
        dest: .prettierrc.json
      - source: configs/stylelint.json
        dest: .stylelintrc.json
      - source: configs/htmlvalidate.json
        dest: .htmlvalidate.json"""

RELEASE_FILES = """\
    files:
      - source: .github/workflow-templates/release.yml
        dest: .github/workflows/release.yaml"""

CLIFF_STABLE_FILES = """\
    files:
      - source: configs/cliff-stable.toml
        dest: cliff.toml"""

CLIFF_ALPHA_FILES = """\
    files:
      - source: configs/cliff-alpha.toml
        dest: cliff.toml"""

HEADER = """\
# Auto-generated by scripts/classify-repos.py — DO NOT EDIT MANUALLY.
# Re-run the script (or let the daily sync workflow do it) to regenerate.

group:"""


def bool_str(value):
    """Render a bool the way the bash script did ('true' / 'false')."""
    return 'true' if value else 'false'


def api_json(path):
    """One `gh api` GET with the per-call timeout; parsed JSON, or None.

    Mirrors the bash `api()` wrapper's call sites, which all silenced stderr
    and fell back on any failure (`2>/dev/null || echo ...`): a timeout, an
    HTTP error, or an unparseable body yields None, never an abort.
    """
    try:
        proc = subprocess.run(
            ['gh', 'api', path], check=False, capture_output=True, text=True, timeout=TIMEOUT
        )
    except subprocess.TimeoutExpired:
        return None
    if proc.returncode != 0:
        return None
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError:
        return None


def tree_paths(repo, recursive):
    """Paths in the repo's HEAD git tree.

    NOTE: GitHub treats ANY `recursive` value — including 0 — as enabling
    recursion, so every call here returns the FULL tree (the bash had the
    same misconception). Classification stays correct because all root
    checks are exact-path matches; collapsing to one tree call per repo is
    a deliberate follow-up, not part of the fidelity port.
    """
    data = api_json(f'repos/{OWNER}/{repo}/git/trees/HEAD?recursive={recursive}')
    if not isinstance(data, dict):
        return []
    return [entry.get('path', '') for entry in data.get('tree') or [] if isinstance(entry, dict)]


def latest_tag(repo):
    """Name of the repo's newest tag: '' when untagged, None when the read
    FAILED.

    Failure must not classify: the bash treated a failed tags read as
    untagged, so a transient API error on a live v0.x repo flipped it to
    the stable cliff tier and the sync auto-merged the wrong cliff.toml.
    """
    data = api_json(f'repos/{OWNER}/{repo}/tags')
    if data is None:
        return None
    if isinstance(data, list) and data and isinstance(data[0], dict):
        return data[0].get('name') or ''
    return ''


def discover_repos():
    """All non-archived cplieger repo names, byte-order sorted.

    The bash sorted with plain `sort`; on the ubuntu-24.04 sync runner
    (LANG=C.UTF-8) that is byte order, which Python's str sort matches
    regardless of the ambient locale.
    """
    try:
        proc = subprocess.run(
            [
                'gh',
                'repo',
                'list',
                OWNER,
                '--limit',
                '300',
                '--json',
                'name,isArchived,primaryLanguage',
            ],
            check=False,
            stdout=subprocess.PIPE,
            text=True,
            timeout=TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        sys.exit(124)  # what `timeout N gh ...` exited with under set -e
    if proc.returncode != 0:
        sys.exit(proc.returncode)  # stderr already passed through, like the bash
    repos = json.loads(proc.stdout)
    names = sorted(repo['name'] for repo in repos if repo.get('isArchived') is False)
    if len(repos) >= 300:
        sys.exit('classify-repos: repo list hit the --limit 300 ceiling; raise the limit')
    return names


def classify(repo):
    """Profile one repo (surfaces, language, cliff tier), mirroring the bash.

    Makes the same API calls in the same order: root tree, a recursive tree
    only for go.mod repos without a root-level web dir, a second recursive
    tree for the image-smoke opt-in (kept separate so failure behavior stays
    call-for-call identical), then the tags read.
    """
    root = tree_paths(repo, '0')
    has_gomod = 'go.mod' in root
    has_jsr = 'jsr.json' in root
    has_pkg = 'package.json' in root
    has_dockerfile = 'Dockerfile' in root
    has_pyproject = 'pyproject.toml' in root
    is_web = 'static-src' in root or 'web' in root

    # go.mod without a root web dir: check for deeper web indicators
    # (e.g. internal/server/static-src, a nested */web/* tree).
    if has_gomod and not is_web:
        deep = tree_paths(repo, '1')
        is_web = any('static-src' in path or '/web/' in path for path in deep)

    # An app opts into the shared image-smoke harness by committing
    # tests/image-smoke.conf; the canonical harness (configs/image-smoke.sh)
    # then syncs to its tests/image-smoke.sh. tests/ is below the root tree,
    # so this needs the recursive listing.
    has_smoke = 'tests/image-smoke.conf' in tree_paths(repo, '1')

    if has_gomod:
        lang = 'go'
    elif has_jsr or has_pkg:
        lang = 'ts'
    elif has_dockerfile:
        lang = 'shell'
    elif has_pyproject:
        lang = 'python'
    else:
        lang = 'none'

    # Cliff tier: default to stable. Only fall back to alpha when the repo is
    # explicitly mid-0.x (latest tag is v0.x). This way fresh/untagged repos
    # get the stable policy so their first release naturally bumps to v1.0.0
    # instead of being trapped at v0.1.0 by alpha's no-major-bump rule.
    tag = latest_tag(repo)
    if tag is None:
        sys.exit(
            f'classify-repos: tags read failed for {repo}; aborting rather than guessing the cliff tier'
        )
    cliff_tier = 'alpha' if tag.startswith('v0.') else 'stable'

    can_release = has_gomod or has_jsr or has_dockerfile
    print(
        f'  classified: {repo:<30} lang={lang:<5} web={bool_str(is_web):<5} '
        f'cliff={cliff_tier:<6} release={bool_str(can_release)}',
        file=sys.stderr,
    )
    return {
        'lang': lang,
        'has_jsr': has_jsr,
        'has_pkg': has_pkg,
        'is_web': is_web,
        'cliff_tier': cliff_tier,
        'has_code': lang in ('go', 'ts'),  # codeql + coverage-badge set
        'can_release': can_release,  # go.mod, jsr.json, or Dockerfile
        'has_smoke': has_smoke,
    }


def print_group(comment, repos, files, *, lead_blank=True):
    """Emit one sync.yml group (comment, repos block, file list) if non-empty."""
    if not repos:
        return
    if lead_blank:
        print()
    print(f'  # {comment}')
    print('  - repos: |')
    for repo in repos:
        print(f'      {OWNER}/{repo}')
    print(files)


def main():
    # Skip the ci repo itself (it is the sync source, never a target).
    repo_names = [name for name in discover_repos() if name != 'ci']

    profiles = {repo: classify(repo) for repo in repo_names}

    # --- Collect repos into groups ---
    ci_repos = []  # ALL releaseable repos -> unified ci.yml
    codeql_repos = []  # go/ts repos (codeql + coverage badge)
    release_repos = []
    cliff_stable = []
    cliff_alpha = []
    golangci_repos = []  # all go repos get .golangci.yaml
    ts_config_repos = []  # ts repos + go-cross-language repos get the TS lint configs
    python_repos = []  # python repos (pyproject.toml) -> ruff.toml + .editorconfig only
    smoke_repos = []  # repos that opted into the shared image-smoke harness

    for repo in repo_names:
        profile = profiles[repo]
        lang = profile['lang']
        if lang == 'none':
            continue

        # Python repos (e.g. the tools methodology repo): lint baseline only —
        # ruff + .editorconfig. Not releaseable, not compiled, so no ci.yml/
        # codeql/release/cliff; they keep their own bespoke ci.yaml.
        if lang == 'python':
            python_repos.append(repo)
            continue

        if profile['has_code']:
            codeql_repos.append(repo)
        if profile['can_release']:
            ci_repos.append(repo)
            release_repos.append(repo)
        if lang == 'go':
            golangci_repos.append(repo)
        if lang == 'ts':
            ts_config_repos.append(repo)
        if profile['has_smoke']:
            smoke_repos.append(repo)
        if profile['cliff_tier'] == 'stable':
            cliff_stable.append(repo)
        else:
            cliff_alpha.append(repo)

    # Cross-language Go repos that ALSO have TS surfaces (e.g.
    # web-terminal-engine: go.mod + web/jsr.json, vibekit/web-terminal-kiro/
    # subflux: go.mod + static-src/) — also need TS lint configs. Appended
    # after the pure-TS repos, in repo order, like the bash's second pass.
    for repo in repo_names:
        profile = profiles[repo]
        if profile['lang'] == 'go' and (
            profile['has_jsr'] or profile['has_pkg'] or profile['is_web']
        ):
            ts_config_repos.append(repo)

    # --- Generate sync.yml ---
    print(HEADER)
    print_group(
        'Unified CI (auto-detects go/ts/web/shell surfaces)',
        ci_repos,
        CI_FILES,
        lead_blank=False,
    )
    print_group('Go-tooling configs (Go-having repos)', golangci_repos, GOLANGCI_FILES)
    print_group(
        'Coverage badge (Go/TS repos — measurable statement coverage)',
        codeql_repos,
        COVERAGE_FILES,
    )
    print_group(
        'Image-smoke harness (repos with a tests/image-smoke.conf opt-in)',
        smoke_repos,
        SMOKE_FILES,
    )
    print_group('Python repos (ruff + editorconfig; bespoke ci.yaml)', python_repos, PYTHON_FILES)
    print_group(
        'TypeScript lint/format configs (TS-having repos, including hybrids)',
        ts_config_repos,
        TS_CONFIG_FILES,
    )
    print_group('Release (unified auto-detect)', release_repos, RELEASE_FILES)
    print_group('Cliff config (stable — v1.x+)', cliff_stable, CLIFF_STABLE_FILES)
    print_group('Cliff config (alpha — v0.x or no tags)', cliff_alpha, CLIFF_ALPHA_FILES)


if __name__ == '__main__':
    main()
