#!/usr/bin/env python3
"""Auto-discover and profile every cplieger repo, printing the sync manifest.

The manifest (.github/sync.yml) goes to stdout, per-repo diagnostics to stderr.
A two-branch repo (release_channels.is_two_branch) is classified once per base
from that base's tree and its groups carry `base:`; every other repo from HEAD.

Importable: `sync_owned_patterns()` is every path the sync can write, and
`canonical_sources(repo)` maps each of them to its source here.

Failure model: the repo listing aborts on an error, a timeout or the page cap;
an unreadable tree drops that repo (or base) from every group; a failed
tags read aborts, because a guessed cliff tier auto-merges the wrong cliff.toml.
"""

import sys
from typing import NamedTuple

import ghrest
import release_channels

OWNER = 'cplieger'
TIMEOUT = 10  # seconds per API call
REST = ghrest.Client(timeout=TIMEOUT)
# A two-branch repo's groups follow every other group, one block per base in this order.
BASES = ('dev', 'main')


class Group(NamedTuple):
    """One manifest group: its comment line and its files, each a path synced
    under its own name or a (source, dest) pair."""

    comment: str
    files: tuple


CI = Group(
    'Unified CI (auto-detects go/ts/web/shell surfaces)',
    (
        '.editorconfig',
        '.gitattributes',
        ('.github/workflow-templates/ci.yml', '.github/workflows/ci.yaml'),
        ('.github/workflow-templates/codeql.yml', '.github/workflows/codeql.yml'),
        ('.github/workflow-templates/security.yml', '.github/workflows/security.yml'),
    ),
)
ARTIFACT_CI = Group(
    'Unified CI for artifact repos (own publish.yaml, no central release.yaml)', CI.files
)
GOLANGCI = Group(
    'Go-tooling configs (Go-having repos)',
    ('.golangci.yaml', ('configs/gremlins.yaml', '.gremlins.yaml')),
)
SMOKE = Group(
    'Image-smoke harness (repos with a tests/image-smoke.conf opt-in)',
    (('configs/image-smoke.sh', 'tests/image-smoke.sh'),),
)
# The assert/extract library and its self-test carry no repo-specific content,
# so they sync; tests/shell/run.sh stays repo-owned because it is the opt-in
# marker, and a synced marker could only arrive once the repo already had it.
SHELL_TEST = Group(
    'Shell unit-test harness (repos with a tests/shell/run.sh opt-in)',
    (
        ('configs/shell/lib.sh', 'tests/shell/lib.sh'),
        ('configs/shell/harness_test.sh', 'tests/shell/harness_test.sh'),
    ),
)
# Keyed on a root Dockerfile rather than an opt-in marker: both scripts are
# inert until a Dockerfile calls them (repin-sha.sh acts only on `# repin:`
# lines; collect-licenses.sh only when the builder stage runs it).
REPIN = Group(
    'sha256 pin recompute helper (image repos; inert without # repin: markers)',
    (
        ('configs/repin-sha.sh', 'scripts/repin-sha.sh'),
        ('configs/collect-licenses.sh', 'scripts/collect-licenses.sh'),
    ),
)
PYTHON = Group(
    'Python repos (ruff + editorconfig; bespoke ci.yaml)',
    ('.editorconfig', '.gitattributes', ('configs/ruff.toml', 'ruff.toml')),
)
TS_CONFIG = Group(
    'TypeScript lint/format configs',
    (
        ('configs/eslint.config.base.mjs', 'eslint.config.base.mjs'),
        ('configs/prettier.json', '.prettierrc.json'),
        ('configs/stylelint.json', '.stylelintrc.json'),
        ('configs/htmlvalidate.json', '.htmlvalidate.json'),
    ),
)
RELEASE = Group(
    'Release (unified auto-detect)',
    (('.github/workflow-templates/release.yml', '.github/workflows/release.yaml'),),
)
CLIFF = {
    'stable': Group(
        'Cliff config (stable — v1.x+)', (('configs/cliff-stable.toml', 'cliff.toml'),)
    ),
    'alpha': Group(
        'Cliff config (alpha — v0.x or no tags)', (('configs/cliff-alpha.toml', 'cliff.toml'),)
    ),
}
TWO_BRANCH_RENOVATE = Group(
    'Two-branch Renovate delta (repos whose default branch is dev)',
    (('configs/renovate-two-branch.json', 'renovate.json'),),
)
# Emission order, for the single-branch block and for each base's; the key
# names the list assign() fills.
GROUPS = (
    ('ci', CI),
    ('artifact_ci', ARTIFACT_CI),
    ('golangci', GOLANGCI),
    ('smoke', SMOKE),
    ('shell_test', SHELL_TEST),
    ('repin', REPIN),
    ('python', PYTHON),
    ('ts_config', TS_CONFIG),
    ('release', RELEASE),
    ('cliff_stable', CLIFF['stable']),
    ('cliff_alpha', CLIFF['alpha']),
    ('two_branch_renovate', TWO_BRANCH_RENOVATE),
)

HEADER = """\
# Auto-generated by scripts/classify-repos.py — DO NOT EDIT MANUALLY.
# Re-run the script (or let the daily sync workflow do it) to regenerate.

group:"""


class ClassifyError(RuntimeError):
    """A read the classification depends on failed; nothing may be guessed from it."""


def pairs(group):
    """The group's files as (source, dest) pairs."""
    return [(f, f) if isinstance(f, str) else f for f in group.files]


def render_files(group):
    lines = ['    files:']
    for entry in group.files:
        if isinstance(entry, str):
            lines.append(f'      - {entry}')
        else:
            lines += [f'      - source: {entry[0]}', f'        dest: {entry[1]}']
    return '\n'.join(lines)


def sync_owned_patterns():
    """Every consumer path any group can write, sorted; reads no API."""
    return sorted({dest for _key, group in GROUPS for _source, dest in pairs(group)})


def canonical_sources(repo):
    """{dest: source path in this repo} for every sync-owned path, with
    cliff.toml resolved by `repo`'s cliff tier. Raises ClassifyError when the
    tags read fails."""
    tier = cliff_tier(repo.split('/')[-1], strict=True)
    sources = {}
    for _key, group in GROUPS:
        if group in CLIFF.values() and group is not CLIFF[tier]:
            continue
        sources.update((dest, source) for source, dest in pairs(group))
    return sources


def bool_str(value):
    return 'true' if value else 'false'


def api_json(path):
    """One GET with the per-call timeout, under ghrest's retry policy; parsed
    JSON, or None on a timeout, an HTTP error or an unparseable body, never an abort."""
    try:
        return REST.get(path)
    except ghrest.ApiError:
        return None


def tree_paths(repo, recursive, ref='HEAD'):
    """Paths in the repo's git tree at `ref`; [] when unreadable.

    GitHub treats ANY `recursive` value, 0 included, as enabling recursion, so
    every call returns the full tree; the root checks are exact-path matches,
    so that stays correct.
    """
    data = api_json(f'repos/{OWNER}/{repo}/git/trees/{ref}?recursive={recursive}')
    if not isinstance(data, dict):
        return []
    return [entry.get('path', '') for entry in data.get('tree') or [] if isinstance(entry, dict)]


def latest_tag(repo, strict=False):
    """Name of the repo's newest STABLE tag (vX.Y.Z): '' when there is none,
    None when the read FAILED. A dev or lane tag is not a root version, so the
    listing pages past them; TagListingTruncatedError when it cannot. Under
    `strict` a page that is not a list of objects with a string `name` failed;
    otherwise it reads as the entries it has, which a main-default repo keeps."""

    def fetch(page):
        data = api_json(
            f'repos/{OWNER}/{repo}/tags?per_page={release_channels.TAG_PAGE_SIZE}&page={page}'
        )
        if data is None:
            return None
        if strict:
            shaped = isinstance(data, list) and all(
                isinstance(e, dict) and isinstance(e.get('name'), str) and e['name'] for e in data
            )
            return [e['name'] for e in data] if shaped else None
        if not isinstance(data, list):
            return []
        return [entry.get('name') or '' for entry in data if isinstance(entry, dict)]

    names = release_channels.collect_tags(fetch, want_stable=1)
    if names is None:
        return None
    return release_channels.newest_stable_tag(names)


def cliff_tier(repo, strict=False):
    """'alpha' when the newest stable tag is v0.x, else 'stable' (so an untagged
    repo's first release bumps to v1.0.0). ClassifyError when the tags read fails;
    `strict` is latest_tag's."""
    try:
        tag = latest_tag(repo, strict)
    except release_channels.TagListingTruncatedError as err:
        msg = f'tags listing of {repo} truncated ({err}); aborting rather than guessing the cliff tier'
        raise ClassifyError(msg) from None
    if tag is None:
        msg = f'tags read failed for {repo}; aborting rather than guessing the cliff tier'
        raise ClassifyError(msg)
    return 'alpha' if tag.startswith('v0.') else 'stable'


def discover_repos():
    """Every non-archived, non-fork cplieger repo as a REST-shaped repository
    object (name, default_branch, visibility, fork, archived), byte-order sorted
    by name.

    Forks are excluded (same rule as audit.py): a fork's tree is UPSTREAM's, so
    syncing our conventions into it rewrites code we do not own.
    """
    try:
        repos = REST.pages('user/repos?affiliation=owner')
    except ghrest.RequestTimeoutError:
        sys.exit(124)  # what `timeout N gh ...` exits with under set -e
    except ghrest.ApiError as err:
        sys.exit(f'classify-repos: repo listing failed: {err}')
    return sorted(
        (
            {
                'name': repo['name'],
                'default_branch': repo.get('default_branch') or '',
                'visibility': str(repo.get('visibility') or '').lower(),
                'fork': False,
                'archived': False,
            }
            for repo in repos
            if repo.get('archived') is False and repo.get('fork') is False
        ),
        key=lambda repo: repo['name'],
    )


def classify(repo, ref='HEAD'):
    """Profile the repo's surfaces and language from its tree at `ref`.

    Calls, in order: the root tree, a recursive tree only for go.mod repos
    without a root-level web dir, then a second recursive tree for the opt-in
    markers. The cliff tier is read separately (cliff_tier).
    """
    root = tree_paths(repo, '0', ref)
    has_gomod = 'go.mod' in root
    has_jsr = 'jsr.json' in root
    has_pkg = 'package.json' in root
    has_dockerfile = 'Dockerfile' in root
    has_pyproject = 'pyproject.toml' in root
    is_web = 'static-src' in root or 'web' in root

    # Deeper web indicators: internal/server/static-src, a nested */web/* tree.
    if has_gomod and not is_web:
        deep = tree_paths(repo, '1', ref)
        is_web = any('static-src' in path or '/web/' in path for path in deep)
    deep_tree = tree_paths(repo, '1', ref)
    has_smoke = 'tests/image-smoke.conf' in deep_tree
    # The same file shell-ci.yaml runs, so enrolment and execution cannot disagree.
    has_shell_tests = 'tests/shell/run.sh' in deep_tree
    # An artifact repo publishes from its own publish.yaml and still needs the
    # meta CI. A marker, not "not releaseable": a repo that releases nothing may
    # keep its own CI, which the sync must never overwrite.
    has_publish = '.github/workflows/publish.yaml' in deep_tree

    if has_gomod:
        lang = 'go'
    elif has_jsr or has_pkg:
        lang = 'ts'
    elif has_dockerfile:
        lang = 'shell'
    elif has_pyproject:
        lang = 'python'
    else:
        lang = 'none'

    return {
        'readable': bool(root),
        'lang': lang,
        'has_jsr': has_jsr,
        'has_pkg': has_pkg,
        'is_web': is_web,
        'can_release': has_gomod or has_jsr or has_dockerfile,
        'has_smoke': has_smoke,
        'has_shell_tests': has_shell_tests,
        'has_dockerfile': has_dockerfile,
        'has_publish': has_publish,  # own publish.yaml -> meta CI without release.yaml
    }


def log_profile(repo, profile, base=None):
    line = (
        f'  classified: {repo:<30} lang={profile["lang"]:<5} web={bool_str(profile["is_web"]):<5} '
        f'cliff={profile["cliff_tier"]:<6} release={bool_str(profile["can_release"])}'
    )
    if base:
        line += f' base={base}' + ('' if profile['readable'] else ' (tree unreadable, skipped)')
    print(line, file=sys.stderr)


def assign(repo_names, profiles):
    """{group key: repos} over `repo_names` (in order) and their profiles."""
    groups = {key: [] for key, _group in GROUPS}
    for repo in repo_names:
        profile = profiles[repo]
        lang = profile['lang']

        # Both opt-ins below resolve BEFORE the lang gate: a repo can carry
        # tested shell or its own publish.yaml while classifying lang=none
        # or lang=python.
        if profile['has_shell_tests']:
            groups['shell_test'].append(repo)
        # can_release keeps the two CI groups disjoint.
        if profile['has_publish'] and not profile['can_release']:
            groups['artifact_ci'].append(repo)

        if lang == 'none':
            continue
        # Lint baseline only; these repos keep their own bespoke ci.yaml.
        if lang == 'python':
            groups['python'].append(repo)
            continue

        if profile['can_release']:
            groups['ci'].append(repo)
            # Its own publish.yaml owns the repo's Releases; a synced release.yaml
            # would cut code Releases marked latest over them.
            if not profile['has_publish']:
                groups['release'].append(repo)
        if lang == 'go':
            groups['golangci'].append(repo)
        if lang == 'ts':
            groups['ts_config'].append(repo)
        if profile['has_smoke']:
            groups['smoke'].append(repo)
        if profile['has_dockerfile']:
            groups['repin'].append(repo)
        groups['cliff_stable' if profile['cliff_tier'] == 'stable' else 'cliff_alpha'].append(repo)

    # Go repos that also have a TS surface need the TS configs too; appended
    # after the pure-TS repos, in repo order.
    for repo in repo_names:
        profile = profiles[repo]
        if profile['lang'] == 'go' and (
            profile['has_jsr'] or profile['has_pkg'] or profile['is_web']
        ):
            groups['ts_config'].append(repo)
    return groups


def print_group(comment, repos, group, *, lead_blank=True, base=None):
    """Emit one sync.yml group (comment, repos block, file list) if non-empty."""
    if not repos:
        return
    if lead_blank:
        print()
    print(f'  # {comment}')
    print('  - repos: |')
    for repo in repos:
        print(f'      {OWNER}/{repo}')
    if base:
        print(f'    base: {base}')
    print(render_files(group))


def main():
    # Skip the ci repo itself (it is the sync source, never a target).
    repos = [repo for repo in discover_repos() if repo['name'] != 'ci']

    single = []
    profiles = {}
    per_base = {base: {} for base in BASES}
    try:
        for repo in repos:
            name = repo['name']
            if release_channels.is_two_branch(repo):
                found = {base: classify(name, base) for base in BASES}
                tier = cliff_tier(name, strict=True)
                for base, profile in found.items():
                    profile['cliff_tier'] = tier
                    log_profile(name, profile, base)
                    if profile['readable']:
                        per_base[base][name] = profile
            else:
                profile = classify(name)
                profile['cliff_tier'] = cliff_tier(name)
                log_profile(name, profile)
                single.append(name)
                profiles[name] = profile
    except ClassifyError as err:
        sys.exit(f'classify-repos: {err}')

    print(HEADER)
    groups = assign(single, profiles)
    for index, (key, group) in enumerate(GROUPS):
        print_group(group.comment, groups[key], group, lead_blank=index > 0)
    for base in BASES:
        names = sorted(per_base[base])
        groups = assign(names, per_base[base])
        groups['two_branch_renovate'] = names
        for key, group in GROUPS:
            print_group(f'{group.comment} (base: {base})', groups[key], group, base=base)


if __name__ == '__main__':
    main()
